[enb]
mcc = 001
mnc = 01
mme_addr = 127.0.1.100
gtp_bind_addr = 127.0.1.1
s1c_bind_addr = 127.0.1.1
n_prb = 50

[enb_files]
sib_config = /home/workspace/conf/sib.conf
rr_config = /home/workspace/conf/rr.conf
drb_config = /home/workspace/conf/drb.conf

[rf]
dl_earfcn = 3350
tx_gain = 80
rx_gain = 40

[pcap]
enable = true
filename = /home/workspace/log/srsLTE_enb.pcap
s1ap_enable = true
s1ap_filename = /home/workspace/log/srsLTE_enb_s1ap.pcap
[log]
all_level = info
all_hex_limit = 32
filename = /home/workspace/log/srsLTE_enb.log
file_max_size = -1

[gui]
enable = false

[scheduler]

[embms]

[channel.dl]

[channel.dl.awgn]

[channel.dl.fading]

[channel.dl.delay]

[channel.dl.rlf]

[channel.dl.hst]

[channel.ul]

[channel.ul.awgn]

[channel.ul.fading]

[channel.ul.delay]

[channel.ul.rlf]

[channel.ul.hst]

[expert]
